CREATE TABLE employer (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(160) NOT NULL);
CREATE TABLE member (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 employer_id BIGINT NOT NULL REFERENCES employer(id), member_number VARCHAR(30) NOT NULL UNIQUE,
 name VARCHAR(160) NOT NULL, birth_date DATE NOT NULL, employment_start DATE NOT NULL,
 status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','RETIRED')),
 version BIGINT NOT NULL DEFAULT 0, CHECK (birth_date < employment_start)
);
CREATE TABLE import_file (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, fingerprint VARCHAR(64) NOT NULL UNIQUE,
 filename VARCHAR(200) NOT NULL, content TEXT NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'RECEIVED'
 CHECK(status IN ('RECEIVED','POSTED','REJECTED','FAILED')),
 submitted_by VARCHAR(100) NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 row_count INT NOT NULL DEFAULT 0
);
CREATE TABLE import_row (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, import_id BIGINT NOT NULL REFERENCES import_file(id),
 row_number INT NOT NULL, member_number VARCHAR(100), payroll_month VARCHAR(100),
 error TEXT, UNIQUE(import_id,row_number)
);
CREATE TABLE contribution (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, member_id BIGINT NOT NULL REFERENCES member(id),
 payroll_month DATE NOT NULL CHECK (extract(day FROM payroll_month)=1),
 pensionable_pay NUMERIC(14,2) NOT NULL CHECK(pensionable_pay>0),
 employee_amount NUMERIC(14,2) NOT NULL CHECK(employee_amount>=0),
 employer_amount NUMERIC(14,2) NOT NULL CHECK(employer_amount>=0),
 import_id BIGINT REFERENCES import_file(id), UNIQUE(member_id,payroll_month)
);
CREATE TABLE benefit_estimate (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, member_id BIGINT NOT NULL REFERENCES member(id),
 as_of DATE NOT NULL, age INT NOT NULL, service_months INT NOT NULL, average_annual_pay NUMERIC(20,8) NOT NULL,
 annual_pension NUMERIC(14,2) NOT NULL, monthly_pension NUMERIC(14,2) NOT NULL,
 eligible BOOLEAN NOT NULL, reason VARCHAR(300) NOT NULL, rule_version VARCHAR(40) NOT NULL,
 inputs_json TEXT NOT NULL, created_by VARCHAR(100) NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE retirement_request (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, estimate_id BIGINT NOT NULL UNIQUE REFERENCES benefit_estimate(id),
 member_id BIGINT NOT NULL REFERENCES member(id), status VARCHAR(20) NOT NULL DEFAULT 'DRAFT'
 CHECK(status IN ('DRAFT','SUBMITTED','APPROVED','REJECTED')),
 created_by VARCHAR(100) NOT NULL, reviewed_by VARCHAR(100), comments VARCHAR(1000),
 created_at TIMESTAMPTZ NOT NULL DEFAULT now(), version BIGINT NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX one_open_request_per_member ON retirement_request(member_id) WHERE status IN ('DRAFT','SUBMITTED','APPROVED');
CREATE TABLE audit_event (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, actor VARCHAR(100) NOT NULL,
 action VARCHAR(80) NOT NULL, entity_type VARCHAR(40) NOT NULL, entity_id BIGINT NOT NULL,
 detail TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE FUNCTION reject_history_change() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN RAISE EXCEPTION 'History is append-only'; END; $$;
CREATE TRIGGER audit_append_only BEFORE UPDATE OR DELETE ON audit_event FOR EACH ROW EXECUTE FUNCTION reject_history_change();
CREATE TRIGGER estimate_immutable BEFORE UPDATE OR DELETE ON benefit_estimate FOR EACH ROW EXECUTE FUNCTION reject_history_change();
CREATE INDEX contribution_member_month ON contribution(member_id,payroll_month DESC);
CREATE INDEX audit_created ON audit_event(created_at DESC);
